<a href="https://colab.research.google.com/github/ahnjihyun/BOOK_Deep-learning-from-scratch-2/blob/main/ch01_1-2%EC%8B%A0%EA%B2%BD%EB%A7%9D%EC%9D%98_%EC%B6%94%EB%A1%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1.2 신경망의 추론 


(p34, 35)

In [ ]:
import numpy as np 

def sigmoid(x):
  return 1 / (1+ np.exp(-x))

x = np.random.randn(10,2) # 입력층 
W1 = np.random.randn(2,4) # 가중치
b1 = np.random.randn(4) # 편향 -> (10,4)로 브로드캐스트 됨
W2 = np.random.randn(4,3)
b2 = np.random.randn(3) # -> (10,3)으로 브로드캐스트

h = np.matmul(x,W1) + b1
a = sigmoid(h) # 비선형성 부여
s = np.matmul(a,W2) + b2

print(s)

[[2.56722803 0.46903913 3.55262971]
 [1.71930537 0.76584932 2.88728482]
 [2.8501313  0.15300436 2.44605562]
 [2.33656261 0.19365464 1.14602745]
 [1.79647008 0.40850689 1.09335386]
 [0.9921855  0.81128525 2.0492017 ]
 [2.55320102 0.23185988 1.71424381]
 [2.80409934 0.06882277 2.58822287]
 [2.46617309 0.16240539 1.25000446]
 [1.37243137 0.58505727 1.26093413]]


---

##### (p35) 1.2.2 계층(Layer)으로 클래스화 및 순전파 구현

In [ ]:
import numpy as np 

class Sigmoid:
  def __init__(self):
    self.params = [] # 시그모이드 계층에는 학습하는 매개변수가 없으므로 인스턴스 변수인 params를 빈 리스트로 초기화 시킴

  def forward(self,x):
    return 1 / (1 + np.exp(-x))

class Affine:
  def __init__(self, W, b): # 초기화 시 가중치와 편향을 갱신
    self.params = [W, b]

  def forward(self,x): # 순전파 처리 구현
    W, b = self.params
    out = np.matmul(x,W) + b
    return out

##### (p38) TwoLayerNet 구현

In [ ]:
class TwoLayerNet:
  def __init__(self, input_size, hidden_size, output_size): ## 이 클래스의 초기화 메서드
    I, H, O = input_size, hidden_size, output_size

    # 가중치와 편향 초기화
    W = np.random.randn(I,H)
    b1 = np.random.randn(H)
    W2 = np.random.randn(H,O)
    b2 = np.random.randn(O)

    # 3개의 계층을 생성
    self.layers = [
      Affine(W1,b1),
      Sigmoid(),
      Affine(W2,b2)
    ]

    # 학습할 모든 가중치를 리스트에 모음
    self.params = []
    for layer in self.layers:
      self.params += layer.params

  def predict(self,x):
    for layer in self.layers:
      x = layer.forward(x)
    return x

# ========

x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3) # input_size, hidden_size, output_size
s = model.predict(x)

print(s)

[[-0.28036537 -1.34207529 -0.02183931]
 [-1.30260286  0.01570365 -0.12240654]
 [-0.79582378 -0.83296787  0.07578486]
 [ 0.17978628 -1.63649671 -0.2397919 ]
 [-0.99114781 -0.66123588 -0.06166759]
 [-1.42687044  0.2460102  -0.11836428]
 [-0.40412896 -1.20974711  0.0252977 ]
 [-0.82305686 -0.75133809  0.06058774]
 [-0.51939592 -1.12178106 -0.10947325]
 [-0.47565566 -0.83960543  0.18803257]]


In [ ]:
# 참고 : 파이썬에서 '+' 연산자는 리스트들을 결합해준다
a = ['A','B']
a += ['C','D']
print(a)

['A', 'B', 'C', 'D']
